### ISSUE TITLE
Openssl version issue with Centos

### ISSUE THREAD

**Issue by bipinacellere** [journeyapps/node-sqlcipher#10]
`Error: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/PATH/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js:4:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
`
It works with Windows and Ubuntu but my centos has openssl 1.0.2k version which is not picking by sqlcipher node module.

> openssl version
> OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by bipinacellere** [comment]
Hi @rkistner 
Can you help on this?

**Comment by rkistner** [comment]
I'm not sure what the best fix is for this, but there are some options:

1. Use a bundled copy of libcrypto, as in this fork: https://github.com/journeyapps/node-sqlcipher/compare/master...scottnonnenberg-signal:updates?expand=1
2. Fix this library to handle version 1.0.2k.

I'm not sure what the exact incompatibility is with version 1.0.2k - nothing in the code is specifically hardcoded to 1.0.0. I also don't have any experience with Centos myself.

**Comment by fholzer** [comment]
* What CentOS version are you on?
* Can you provide the output of `ls -l /usr/lib*/libcrypto.so*`?
* Can you provide the output of `find node_modules/@journeyapps/sqlcipher/lib/binding/ -type f | xargs ldd`

**Comment by rkistner** [comment]
Closing due to lack of info.
