### ISSUE TITLE
CentOS 7 - libcrypto.so.1.1 not found

### ISSUE THREAD

**Issue by Gerrit0** [journeyapps/node-sqlcipher#23]
Everything works great on Windows, but Cent OS 7 doesn't seem to like my setup.

```text
internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: libcrypto.so.1.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gerrit/project/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

As I saw this mentioned in another issue:

```bash
$ ls -l /usr/lib*/libcrypto.so*
lrwxrwxrwx. 1 root root      19 Oct 29 19:30 /usr/lib64/libcrypto.so -> libcrypto.so.1.0.2k
lrwxrwxrwx. 1 root root      19 Oct 29 19:30 /usr/lib64/libcrypto.so.10 -> libcrypto.so.1.0.2k
-rwxr-xr-x. 1 root root 2521144 Aug  8 19:38 /usr/lib64/libcrypto.so.1.0.2k
```

The readme mentions OpenSSL 1.0.2n bundled install on Windows, I tried installing 1.0.2t since it was the most recent version with the same major/minor/patch listed here: https://www.openssl.org/source/, but this gives a different error:

```
internal/modules/cjs/loader.js:1003
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/gerrit/project/node_modules/@journeyapps/sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/gerrit/CS-3160-Final-Project/node_modules/@journeyapps/sqlcipher/lib/sqlite3.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
```

Am I missing something obvious?

**Comment by Gerrit0** [comment]
I tried this again, this time with 1.0.2n in case that made a difference, but no luck.

**Comment by gms1** [comment]
```
Error: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```
so it looks like it depends on openssl 1.1 (  in the readme mentioned as a requirement for Mac )

**Comment by Gerrit0** [comment]
I tried installing 1.1 and also ran into the same CXXABI issue, so I just gave up on Cent OS and switched to a VM with a newer version of Ubuntu & everything worked perfectly first time.
