### ISSUE TITLE
Not valid Win32 application before update to 4.1.0

### ISSUE THREAD

**Issue by ajmasia** [journeyapps/node-sqlcipher#35]
Ho @rkistner, I've updated the library from 4.0.0 to 4.1.0 and get this error when compiling to windows using electron 8.0.0:

`Not valid Win32 application before update to 4.1.0`

Compiling for Mac or Linux work fine 😄 

Any idea?

Thanks!

**Comment by rkistner** [comment]
Need more info to debug this issue.

1. What are the exact steps you are performing to get this error?
2. What exactly is producing that error? E.g. when installing or running?
3. Do you have more logs before / after the error?

That error is typical if you're using a 64-bit library in a 32-bit application or vice versa.

**Comment by ajmasia** [comment]
Hi @rkistner, just update electron version from 6.0.0 to 8.0.0
1. Update the electron version, get new windows build and get the error when the app starts
2. When the build app starts.
3. No, only the popup error message in windows.

When use electron 6.0.0 works fine.
I'm using yarn to install and rebuild all dependencies.
I've noted than when to use an electron 8.0.0 version, rebuild takes much longer than in version 6.0.0

**Comment by ajmasia** [comment]
When trying build for windows you get the next error (in this case using electron 7):

```bash
 electron-builder install-app-deps
  • electron-builder  version=22.7.0
  • rebuilding native dependencies  dependencies=@journeyapps/sqlcipher@4.1.0 platform=win32 arch=x64
  • rebuilding native dependency  name=@journeyapps/sqlcipher version=4.1.0
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.4
    $ node-pre-gyp install --fallback-to-build
    Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\...\node_modules\node-gyp\bin\node-gyp.js c
onfigure --fallback-to-build --module=C:\Users\...\node_modules\@journeyapps\sqlcipher\lib\binding\electron-
v7.3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\...\node_modules\@journey
apps\sqlcipher\lib\binding\electron-v7.3-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-
v7.3' (1)
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=node-pre-gyp info it worked if it ends with ok
    node-pre-gyp info using node-pre-gyp@0.11.0
    node-pre-gyp info using node@12.18.2 | win32 | x64
    node-pre-gyp WARN Using request for node-pre-gyp https download
    node-pre-gyp http GET https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v4.1.0/electron-v7.3-win32-x64.tar.gz
    node-pre-gyp http 403 https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v4.1.0/electron-v7.3-win32-x64.tar.gz
    node-pre-gyp WARN Tried to download(403): https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v4.1.0/electron-v7.3-
win32-x64.tar.gz
    node-pre-gyp WARN Pre-built binaries not found for @journeyapps/sqlcipher@4.1.0 and electron@7.3.2 (electron-v7.3 ABI, unknown) (fallin
g back to source compile with node-gyp)
    node-pre-gyp http 403 status code downloading tarball https://journeyapps-node-binary.s3.amazonaws.com/@journeyapps/sqlcipher/v4.1.0/el
ectron-v7.3-win32-x64.tar.gz
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@12.18.2 | win32 | x64
    gyp info ok
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@12.18.2 | win32 | x64
    gyp ERR! configure error
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\...\node_modules\node-gyp\lib\configure.js:484
:19)
    gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\...\node_modules\node-gyp\lib\configure.js:509:
16)
    gyp ERR! stack     at callback (C:\Users\...\node_modules\graceful-fs\polyfills.js:295:20)
    gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
    gyp ERR! System Windows_NT 10.0.18363
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\node_modules\\node-gyp\\bin\\n
ode-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\...\\node_modules\\@journeyapps\\sqlcip
her\\lib\\binding\\electron-v7.3-win32-x64\\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\Users\\...\\...\\node_modules\\@journeyapps\\sqlcipher\\lib\\binding\\electron-v7.3-win32-x64" "--napi_version=6" "--node_abi_napi=napi" "-
-napi_build_version=0" "--node_napi_label=electron-v7.3"
    gyp ERR! cwd C:\Users\...\node_modules\@journeyapps\sqlcipher
    gyp ERR! node -v v12.18.2
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    node-pre-gyp ERR! build error
    node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\...\node_mod
ules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\...\node_modules\@journeyapps\
sqlcipher\lib\binding\electron-v7.3-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\...\...\node_modules\@journeyapps\sqlcipher\lib\binding\electron-v7.3-win32-x64 --napi_version=6 --node_abi_napi=napi --napi_build_versio
n=0 --node_napi_label=electron-v7.3' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\...\node_modules\node-pre-gyp\lib\util
\compile.js:83:29)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
    node-pre-gyp ERR! System Windows_NT 10.0.18363
    node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\node_modules\\node-pr
e-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd C:\Users\...\node_modules\@journeyapps\sqlcipher
    node-pre-gyp ERR! node -v v12.18.2
    node-pre-gyp ERR! node-pre-gyp -v v0.11.0
    node-pre-gyp ERR! not ok
    error Command failed with exit code 1.


                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files (x86)\Yarn\bin\yarn.js' run install
                    workingDir=C:\Users\...\node_modules\@journeyapps\sqlcipher
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by rkistner** [comment]
prebuilt binaries are currently available for electron 6.1, 7.1, and 8.1. (I would have expected the same version to be used for all the 7.x versions, but seems like that is not the case here).

A future version will using NAPI, which will reduce these issues (only a single pre-built version will work with all node & electron versions). However, that will require some work to migrate.

In the meantime, the rebuild scripts should work if you follow the node-gyp setup instructions:
https://github.com/nodejs/node-gyp#on-windows

**Comment by ajmasia** [comment]
> prebuilt binaries are currently available for electron 6.1, 7.1, and 8.1. (I would have expected the same version to be used for all the 7.x versions, but seems like that is not the case here).
> 
> A future version will using NAPI, which will reduce these issues (only a single pre-built version will work with all node & electron versions). However, that will require some work to migrate.
> 
> In the meantime, the rebuild scripts should work if you follow the node-gyp setup instructions:
> https://github.com/nodejs/node-gyp#on-windows

Only work for electron 6.1 😄

**Comment by ajmasia** [comment]
Hi @rkistner, I've checked again and works fine for electron 8.1.1 and 7.1.1 too.
Good Job! Thanks! 😄

**Comment by jianfenkezhan** [comment]
Same issue happen to electron 8.2.5 , how to fix?

**Comment by rkistner** [comment]
Version 5.0.0 has been released, which uses N-API and includes pre-built binaries supporting Electron 6+ and Node 10+ (including future Node and Electron versions).
