### ISSUE TITLE
Build fails on Linux with "not a gzip file"

### ISSUE THREAD

**Issue by olof-nord** [journeyapps/node-sqlcipher#45]
I am trying to build this on Linux, but to no avail.

Any idea what I am doing wrong?

using latest `master`, Linux x64, Arch Linux, node v12.13.0

I have tried with Python 2.7 and with Python 3.8.5, see below for logs:

PYTHON 3:
```log
make verbose
./node_modules/.bin/node-pre-gyp rebuild --loglevel=verbose
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
node-pre-gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'rebuild',
node-pre-gyp verb cli   '--loglevel=verbose'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.13.0 | linux | x64
node-pre-gyp verb command rebuild []
node-pre-gyp verb command clean []
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64',
gyp verb cli   '--napi_version=5',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v72'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/usr/bin/python3"
gyp verb find Python - executing "/usr/bin/python3" to get version
gyp verb find Python - version is "3.8.5"
gyp info find Python using Python version 3.8.5 found at "/usr/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 12.13.0
gyp verb command install [ '12.13.0' ]
gyp verb install input version string "12.13.0"
gyp verb install installing version: 12.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.13.0
gyp verb build dir attempting to create "build" dir: /home/olof/git/node-sqlcipher/build
gyp verb build dir "build" dir needed to be created? /home/olof/git/node-sqlcipher/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/olof/git/node-sqlcipher/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/olof/git/node-sqlcipher/config.gypi
gyp verb common.gypi checking for gypi file: /home/olof/git/node-sqlcipher/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/git/node-sqlcipher/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/olof/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/olof/git/node-sqlcipher/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/olof/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/olof/git/node-sqlcipher',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64',
gyp verb cli   '--napi_version=5',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v72'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/olof/.cache/node-gyp/12.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/home/olof/git/node-sqlcipher/build'
  LD_LIBRARY_PATH=/home/olof/git/node-sqlcipher/build/Release/lib.host:/home/olof/git/node-sqlcipher/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /home/olof/git/node-sqlcipher/build/Release/obj/gen/sqlcipher-amalgamation-3031000; python ./extract.py ./sqlcipher-amalgamation-3031000.tar.gz "/home/olof/git/node-sqlcipher/build/Release/obj/gen"
Traceback (most recent call last):
  File "/usr/lib/python3.8/tarfile.py", line 1672, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1649, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1512, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.8/tarfile.py", line 2313, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.8/tarfile.py", line 1102, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./extract.py", line 7, in <module>
    tfile = tarfile.open(tarball,'r:gz');
  File "/usr/lib/python3.8/tarfile.py", line 1619, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1676, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
make[1]: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlcipher-amalgamation-3031000/sqlite3.c] Error 1
make[1]: Leaving directory '/home/olof/git/node-sqlcipher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/olof/git/node-sqlcipher/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.8.10-arch1-1
gyp ERR! command "/home/olof/.nvm/versions/node/v12.13.0/bin/node" "/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js" "build" "--loglevel=verbose" "--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/olof/git/node-sqlcipher
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/olof/.nvm/versions/node/v12.13.0/bin/node /home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/olof/git/node-sqlcipher/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.8.10-arch1-1
node-pre-gyp ERR! command "/home/olof/.nvm/versions/node/v12.13.0/bin/node" "/home/olof/git/node-sqlcipher/node_modules/.bin/node-pre-gyp" "rebuild" "--loglevel=verbose"
node-pre-gyp ERR! cwd /home/olof/git/node-sqlcipher
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/olof/.nvm/versions/node/v12.13.0/bin/node /home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
make: *** [Makefile:15: verbose] Error 1
```

PYTHON 2:
```log
make verbose                  
./node_modules/.bin/node-pre-gyp rebuild --loglevel=verbose
node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
node-pre-gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/.bin/node-pre-gyp',
node-pre-gyp verb cli   'rebuild',
node-pre-gyp verb cli   '--loglevel=verbose'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.11.0
node-pre-gyp info using node@12.13.0 | linux | x64
node-pre-gyp verb command rebuild []
node-pre-gyp verb command clean []
node-pre-gyp verb command build [ 'rebuild' ]
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'configure',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64',
gyp verb cli   '--napi_version=5',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v72'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python checking Python explicitly set from environment variable PYTHON
gyp verb find Python - process.env.PYTHON is "/usr/bin/python2"
gyp verb find Python - executing "/usr/bin/python2" to get executable path
gyp verb find Python - executable path is "/usr/bin/python2"
gyp verb find Python - executing "/usr/bin/python2" to get version
gyp verb find Python - version is "2.7.18"
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python2"
gyp verb get node dir no --target version specified, falling back to host node version: 12.13.0
gyp verb command install [ '12.13.0' ]
gyp verb install input version string "12.13.0"
gyp verb install installing version: 12.13.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 12.13.0
gyp verb build dir attempting to create "build" dir: /home/olof/git/node-sqlcipher/build
gyp verb build dir "build" dir needed to be created? /home/olof/git/node-sqlcipher/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /home/olof/git/node-sqlcipher/build/config.gypi
gyp verb config.gypi checking for gypi file: /home/olof/git/node-sqlcipher/config.gypi
gyp verb common.gypi checking for gypi file: /home/olof/git/node-sqlcipher/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/git/node-sqlcipher/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/olof/.cache/node-gyp/12.13.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/olof/.cache/node-gyp/12.13.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/olof/git/node-sqlcipher/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/olof/.cache/node-gyp/12.13.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/olof/git/node-sqlcipher',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/home/olof/.nvm/versions/node/v12.13.0/bin/node',
gyp verb cli   '/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'build',
gyp verb cli   '--loglevel=verbose',
gyp verb cli   '--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node',
gyp verb cli   '--module_name=node_sqlite3',
gyp verb cli   '--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64',
gyp verb cli   '--napi_version=5',
gyp verb cli   '--node_abi_napi=napi',
gyp verb cli   '--napi_build_version=0',
gyp verb cli   '--node_napi_label=node-v72'
gyp verb cli ]
gyp info using node-gyp@6.1.0
gyp info using node@12.13.0 | linux | x64
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/olof/.cache/node-gyp/12.13.0
gyp verb `which` succeeded for `make` /usr/bin/make
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make[1]: Entering directory '/home/olof/git/node-sqlcipher/build'
  LD_LIBRARY_PATH=/home/olof/git/node-sqlcipher/build/Release/lib.host:/home/olof/git/node-sqlcipher/build/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps; mkdir -p /home/olof/git/node-sqlcipher/build/Release/obj/gen/sqlcipher-amalgamation-3031000; python ./extract.py ./sqlcipher-amalgamation-3031000.tar.gz "/home/olof/git/node-sqlcipher/build/Release/obj/gen"
Traceback (most recent call last):
  File "/usr/lib/python3.8/tarfile.py", line 1672, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1649, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1512, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.8/tarfile.py", line 2313, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.8/tarfile.py", line 1102, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.8/gzip.py", line 292, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.8/gzip.py", line 479, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.8/gzip.py", line 427, in _read_gzip_header
    raise BadGzipFile('Not a gzipped file (%r)' % magic)
gzip.BadGzipFile: Not a gzipped file (b've')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./extract.py", line 7, in <module>
    tfile = tarfile.open(tarball,'r:gz');
  File "/usr/lib/python3.8/tarfile.py", line 1619, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1676, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
make[1]: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlcipher-amalgamation-3031000/sqlite3.c] Error 1
make[1]: Leaving directory '/home/olof/git/node-sqlcipher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/olof/git/node-sqlcipher/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.8.10-arch1-1
gyp ERR! command "/home/olof/.nvm/versions/node/v12.13.0/bin/node" "/home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js" "build" "--loglevel=verbose" "--module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /home/olof/git/node-sqlcipher
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/olof/.nvm/versions/node/v12.13.0/bin/node /home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/olof/git/node-sqlcipher/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Linux 5.8.10-arch1-1
node-pre-gyp ERR! command "/home/olof/.nvm/versions/node/v12.13.0/bin/node" "/home/olof/git/node-sqlcipher/node_modules/.bin/node-pre-gyp" "rebuild" "--loglevel=verbose"
node-pre-gyp ERR! cwd /home/olof/git/node-sqlcipher
node-pre-gyp ERR! node -v v12.13.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/home/olof/.nvm/versions/node/v12.13.0/bin/node /home/olof/git/node-sqlcipher/node_modules/node-gyp/bin/node-gyp.js build --loglevel=verbose --module=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/olof/git/node-sqlcipher/lib/binding/node-v72-linux-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
make: *** [Makefile:15: verbose] Error 1

```

**Comment by rkistner** [comment]
The `deps/sqlcipher-amalgamation-3031000.tar.gz` file is managed with git-lfs - you'll need to setup git-lfs if you want to develop on this locally.

**Comment by olof-nord** [comment]
Many thanks! Once `git lfs` was installed and initialised, the build succeeds without any problems.
