### ISSUE TITLE
Version 5.0.0 doesn't compile on MacOS Catalina 10.15.7

### ISSUE THREAD

**Issue by jepiqueau** [journeyapps/node-sqlcipher#57]
**node -v** : v12.18.3

**MacOS Catalina** 10.15.7

I have install the package with
`npm install --save @journeyapps/sqlcipher`

see  `package.json` file below

```
{
  "name": "my-electron-sqlite",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "keywords": [],
  "author": "",
  "license": "ISC",

  "scripts": {
    "build": "npm run electron:tsc",
    "electron:tsc": "tsc main.ts",
    "start": "electron .",
    "postinstall": "electron-rebuild ",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "@journeyapps/sqlcipher": "^5.0.0"
  },
  "devDependencies": {
    "@types/sqlite3": "^3.1.6",
    "electron": "^10.1.5",
    "electron-is-dev": "^1.2.0",
    "electron-rebuild": "^2.3.2",
    "tslib": "^2.0.3",
    "typescript": "^3.9.7"
  }
}
```

error when running `npm run postinstall`
```
⠏ Building module: sqlcipher, Completed: 03 warnings and 8 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/backup.o] Error 1
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite/node_modules/@journeyapps/sqlcipher'.
Error: `make` failed with exit code: 2

Error: node-gyp failed to rebuild '/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite/node_modules/@journeyapps/sqlcipher'.
Error: `make` failed with exit code: 2
    at ModuleRebuilder.rebuildNodeGypModule (/Users/queaujeanpierre/Documents/ElectronProjects/my-electron-sqlite/node_modules/electron-rebuild/lib/src/module-rebuilder.js:193:19)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

i step back to `@journeyapps/sqlcipher@4.1.0` and the `npm run postinstall` works fine.

Any idea?

**Comment by Kepro** [comment]
well there is a lot of error messages above the text you wrote here :) but same issue for me...

**Comment by jepiqueau** [comment]
I will close this issue, in fact we do not need to use `electron-rebuild`, 
the `npm i --save @journeyapps/sqlcipher`  is enough to have it working
