### ISSUE TITLE
Webpack node-sqlcipher

### ISSUE THREAD

**Issue by nimeshkan** [journeyapps/node-sqlcipher#62]
I tried to add to mozilla-iot code , @ry @journeyapps/sqlcipher
gateway/build/webpack:/src/sqlcipher/lib sync:2
	var e = new Error("Cannot find module '" + req + "'");
^
Error: Cannot find module gateway/src/sqlcipher/lib/binding/napi-v6-linux-x64/node_sqlite3.node'
    at webpackEmptyContext (gateway/build/webpack:/src/sqlcipher/lib sync:2:1)
    at Object.<anonymous> (gateway/build/webpack:/src/sqlcipher/lib/sqlite3-binding.js:4:15)
    at Object../src/sqlcipher/lib/sqlite3-binding.js gateway/build/gateway.js:17792:30)
    at __webpack_require__ (/gateway/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/sqlcipher/lib/sqlite3.js (gateway/build/webpack:/src/sqlcipher/lib/sqlite3.js:2:15)
    at __webpack_require__ (/home/nimesh/workspace/XERUS/HUB/Sriharsha-alert/gateway/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/sqlcipher/sqlite3.js (gateway/build/webpack:/src/sqlcipher/sqlite3.js:1:18)
    at __webpack_require__ (gateway/build/webpack:/webpack/bootstrap:19:1)
    at Object../src/db.js gateway/build/webpack:/src/db.js:15:19)
    at __webpack_require__ (gateway/build/webpack:/webpack/bootstrap:19:1)

**Comment by rkistner** [comment]
Native node modules are in general not well suited for webpack.

You should be able to exclude it from bundling by using [externals](https://webpack.js.org/configuration/externals/), for example:

```js
module.exports = {
  // ...
  externals: {
    '@journeyapps/sqlcipher': 'commonjs2 @journeyapps/sqlcipher',
  }
};
```

(not tested, and will depend on your specific setup)
