### ISSUE TITLE
Building for Windows from OSX

### ISSUE THREAD

**Issue by jonhewines** [journeyapps/node-sqlcipher#9]
Hi!

I'm building from an OSX environment, using Electron v1.8.7

I've been able to successfully build my electron app for OSX with node-sqlcipher, but when I try to build for Windows I get the following error:

```
Uncaught Error: The specified module could not be found.
\\?\C:\Users\USER_NAME\AppData\Local\Temp\0729404d-1f94-4f70-b897-4282e4d00c92.tmp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([FILE_PATH]\resources\app.asar\node_modules\@journeyapps\sqlcipher\lib\sqlite3.js:4:15)
    at Object.<anonymous> ([FILE_PATH]\resources\app.asar\node_modules\@journeyapps\sqlcipher\lib\sqlite3.js:190:3)
```

In my build command, I am using `electron-builder install-app-deps --platform=win32 && cross-env BUILD_TARGET=win32` before executing my build. This was required to build platform-dependent binaries and get other modules working across platforms (e.g. keytar, sqlite3)

If it is any help, in `node_modules/@journeyapps/sqlcipher/lib/binding/electron-v1.8-win32-x64` I can see the following: 

- libeay32.dll
- msvcr120.dll
- node_sqlite3.node

which makes me think the binaries are there but aren't being included in the build?

Any help massively appreciated!

**Comment by jonhewines** [comment]
FYI, I have openssl installed via brew

**Comment by jonhewines** [comment]
I've just tried extracting app.asar, and can also see the file listed above included in the asar package

**Comment by jonhewines** [comment]
And, I've just confirmed that the module that ''can't be found', does actually exist, i.e;

`C:\Users\USER_NAME\AppData\Local\Temp\0729404d-1f94-4f70-b897-4282e4d00c92.tmp.node`

**Comment by jonhewines** [comment]
I figured it out! I just needed to copy `libeay32.dll` into the electron build directory

Hope this was helpful to someone, otherwise it was just a weird conversation with myself

**Comment by rkistner** [comment]
While it's not explicitly supported to cross-compile, it does seem like you have found a workaround. Closing this issue.
